### ISSUE TITLE
Annotations in YML files

### ISSUE THREAD

**Issue by torkelrogstad** [alta/protopatch#17]
Is it possible to write protopatch annotations in a separate YML file, instead of in the Proto file? That way I can avoid importing the protopatch Proto file, which is great if I want to distribute the Proto files to others so they can compile them for their platform/language.

**Comment by ydnar** [comment]
I suppose it's possible. How do you imagine that working?

**Comment by torkelrogstad** [comment]
TBH I have no idea how to implement it. But the usage would be similar to how [gRPC Gateway]()https://github.com/grpc-ecosystem/grpc-gateway) implements HTTP annotations: 

EIther, you can annotate RPCs directly: 

```proto3
import "google/api/annotations.proto"; 

service Foo {
  rpc Bar(Request) returns (Response {
    option (google.api.http) = {
      post : "/foo/bar"
      body : "*"
    };
  }
}

message Request {
  string field1 = 1;
}

message Response {
  string field1 = 1;
}
```

Or you can write them in a separate file, leaving your Proto file like this: 

```proto3
service Foo {
  rpc Bar(Request) returns (Response {}
}

message Request {
  string field1 = 1;
}

message Response {
  string field1 = 1;
}
```

And add a YML file like this: 

```yml
type: google.api.Service
config_version: 3

http:
  rules:
    - selector: Foo.Bar
      post: /foo/bar
      body: '*'
```

Which you would then pass in as a CLI parameter when compiling the Proto file: `protoc  --grpc-gateway_opt grpc_api_configuration=annotations.yml ...`

For protopatch I could imagine something similar, where the YML file could be something like this: 

```yml
protopatch: 
  - selector: Response
    field: 
      tags: "custom-tag: custom-value"
```

Sorry for being of so little use on the imlementation part! But what do you think of this sort of config file API?
