### ISSUE TITLE
Support running plugins with go1.24's "go tool" pattern

### ISSUE THREAD

**Issue by nvx** [alta/protopatch#181]
Instead of running protoc plugins as `protoc-gen-tool` running them as `go tool protoc-gen-tool` would allow tool version management to occur within the go.mod file simplifying tool management.

A flag to control the behaviour would make sense

**Comment by meling** [comment]
Not sure I understand how you would use the flag to replace something like this: 
```sh
protoc \
	-I . \
	-I `go list -m -f {{.Dir}} github.com/alta/protopatch` \
	-I `go list -m -f {{.Dir}} google.golang.org/protobuf` \
	--go-patch_out=plugin=go,paths=source_relative:. \
	--go-patch_out=plugin=go-grpc,paths=source_relative:. \
	*.proto
```

**Comment by nvx** [comment]
> Not sure I understand how you would use the flag to replace something like this:
> 
> protoc \
> 	-I . \
> 	-I `go list -m -f {{.Dir}} github.com/alta/protopatch` \
> 	-I `go list -m -f {{.Dir}} google.golang.org/protobuf` \
> 	--go-patch_out=plugin=go,paths=source_relative:. \
> 	--go-patch_out=plugin=go-grpc,paths=source_relative:. \
> 	*.proto

it's not about managing proto dependencies (I personally use buf for that side of things), but rather about managing the `protoc-gen-go` tool itself. Check out https://tip.golang.org/doc/modules/managing-dependencies#tools and the Go1.24 release notes for more information about the pattern, but the tldr is it means you wouldn't need to have protoc-gen-* tools installed or manage the version of them and instead which version is used gets managed by the version referenced in the go.mod file. This is super handy for projects with multiple developers as you no longer have to rely on the version installed on their machine when regenerating the protos.

**Comment by meling** [comment]
I’m aware of the 1.24 tool dependency in go.mod feature. I just didn’t understand how to use the flag to take advantage of it. Could you give a usage example; will it only work with buf?

**Comment by nvx** [comment]
> I’m aware of the 1.24 tool dependency in go.mod feature. I just didn’t understand how to use the flag to take advantage of it. Could you give a usage example; will it only work with buf?

oh you mean how the specific implementation I PR'd in #182 works? if so `--go-patch_out=plugin=go,paths=source_relative:.` would become `--go-patch_out=plugin=go,paths=source_relative,use_go_tool=true:.` which would have the effect of running `go tool protoc-gen-go` instead of `protoc-gen-go`

It would work both with and without buf, but if you're not using buf then the proto dependency management is up to you still (I imagine your go list example would still work for example)

For buf something like this would work in your buf.gen.yaml:

```
version: v2
plugins:
  - local: [go,tool,protoc-gen-go-patch]
    out: .
    opt:
      - plugin=go
      - use_go_tool=true
```

**Comment by meling** [comment]
FYI, I go it to work without the flag:
```yaml
version: v2
plugins:
- local: [ "go", "tool", "protoc-gen-go-patch" ]
  out: ./
  opt:
  - plugin=go
  - paths=source_relative
- local: [ "go", "tool", "protoc-gen-connect-go" ]
  out: ./
  opt:
  - paths=source_relative
```
Not sure why you need the flag...
